language: java
install:
  - ./gradlew setupCIWorkspace
  - branch=$(git rev-parse --abbrev-ref HEAD)
  - sed -i 's:^[ \t]*version[ \t]*=\([ \t]*.*\)$:version=\1-'"$branch"':' build.properties
  -  sed -i 's:^[ \t]*build_number[ \t]*=\([ \t]*.*\)$:build_number=\1-SNAPSHOT:' build.properties
script:
  - ./gradlew build uploadArchives
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
jdk:
  - oraclejdk8
